=== pacsbrasil/dcm4che2/dcm4chee/dcm4chee-arc/trunk/dcm4jboss-ejb/src/etc/conf/dcm4jboss-attribute-filter.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
This is the XML DTD for the dcm4jboss attribute filter descriptor.

Minimal descriptor for DICOM Standard Conformance of Query/Retrieve Service:
  <dcm4jboss-attribute-filter>
    <filter level="PATIENT">
      <attr tag="(0008,0005)"/>
      <attr tag="(0010,0010)"/>
      <attr tag="(0010,0020)"/>
    </filter>

    <filter level="STUDY">
      <attr tag="(0008,0005)"/>
      <attr tag="(0008,0020)"/>
      <attr tag="(0008,0030)"/>
      <attr tag="(0008,0050)"/>
      <attr tag="(0020,000D)"/>
      <attr tag="(0020,0010)"/>
    </filter>

    <filter level="SERIES">
      <attr tag="(0008,0005)"/>
      <attr tag="(0008,0060)"/>
      <attr tag="(0020,000E)"/>
      <attr tag="(0020,0011)"/>
    </filter>

    <filter level="IMAGE">
      <attr tag="(0008,0005)"/>
      <attr tag="(0008,0018)"/>
      <attr tag="(0020,0013)"/>
    </filter>
  </dcm4jboss-attribute-filter>
-->

<!ELEMENT dcm4jboss-attribute-filter (filter)*>
<!ELEMENT filter (attr)*>
<!ELEMENT attr EMPTY>
<!ATTLIST filter level (PATIENT | STUDY | SERIES | IMAGE) #REQUIRED>
<!ATTLIST filter exclude (true | false )  "false">
<!ATTLIST attr tag CDATA #REQUIRED>

=== pacsbrasil/dcm4che2/dcm4chee/dcm4chee-arc/trunk/dcm4jboss-ejb/src/etc/conf/dcm4jboss-attribute-filter-all-attrs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dcm4jboss-attribute-filter SYSTEM "dcm4jboss-attribute-filter.dtd">
<dcm4jboss-attribute-filter>
  <filter level="PATIENT">
<!-- Specific Character Set -->
    <attr tag="(0008,0005)"/>
<!-- Patient's Name -->
    <attr tag="(0010,0010)"/>
<!-- Patient ID -->
    <attr tag="(0010,0020)"/>
<!-- Issuer of Patient ID -->
    <attr tag="(0010,0021)"/>
<!-- Patient's Birth Date -->
    <attr tag="(0010,0030)"/>
<!-- Patient's Sex -->
    <attr tag="(0010,0040)"/>
  </filter>
  
  <filter level="STUDY">
<!-- Specific Character Set -->
    <attr tag="(0008,0005)"/>
<!-- Study Date -->
    <attr tag="(0008,0020)"/>
<!-- Study Time -->
    <attr tag="(0008,0030)"/>
<!-- Accession Number -->
    <attr tag="(0008,0050)"/>
<!-- Referring Physician Name -->
    <attr tag="(0008,0090)"/>
<!-- Study Description -->
    <attr tag="(0008,1030)"/>
<!-- Procedure Code Seq -->
    <attr tag="(0008,1032)"/>
<!-- Study Instance UID -->
    <attr tag="(0020,000D)"/>
<!-- Study ID -->
    <attr tag="(0020,0010)"/>
  </filter>
  
  <filter level="SERIES">
<!-- Specific Character Set -->
    <attr tag="(0008,0005)"/>
<!-- Series Date -->
    <attr tag="(0008,0021)"/>
<!-- Series Time -->
    <attr tag="(0008,0031)"/>
<!-- Modality -->
    <attr tag="(0008,0060)"/>
<!-- Manufacturer -->
    <attr tag="(0008,0070)"/>
<!-- Series Description -->
    <attr tag="(0008,103E)"/>
<!-- Manufacturer Model Name -->
    <attr tag="(0008,1090)"/>
<!-- Referenced Performed Procedure Step Sequence -->
    <attr tag="(0008,1111)"/>
<!-- Body Part Examined -->
    <attr tag="(0018,0015)"/>
<!-- Series Instance UID -->
    <attr tag="(0020,000E)"/>
<!-- Series Number -->
    <attr tag="(0020,0011)"/>
<!-- Laterality -->
    <attr tag="(0020,0060)"/>
<!-- Performed Procedure Step Start Date -->
    <attr tag="(0040,0244)"/>
<!-- Performed Procedure Step Start Time -->
    <attr tag="(0040,0245)"/>
<!-- Request Attributes Sequence -->
    <attr tag="(0040,0275)"/>
  </filter>
  
  <filter level="IMAGE" exclude="true">
<!-- Patient Attributes -->
<!-- Patient's Name -->
    <attr tag="(0010,0010)"/>
<!-- Patient ID -->
    <attr tag="(0010,0020)"/>
<!-- Issuer of Patient ID -->
    <attr tag="(0010,0021)"/>
<!-- Patient's Birth Date -->
    <attr tag="(0010,0030)"/>
<!-- Patient's Sex -->
    <attr tag="(0010,0040)"/>

<!-- Study Attributes -->
<!-- Study Date -->
    <attr tag="(0008,0020)"/>
<!-- Study Time -->
    <attr tag="(0008,0030)"/>
<!-- Accession Number -->
    <attr tag="(0008,0050)"/>
<!-- Referring Physician Name -->
    <attr tag="(0008,0090)"/>
<!-- Study Description -->
    <attr tag="(0008,1030)"/>
<!-- Procedure Code Seq -->
    <attr tag="(0008,1032)"/>
<!-- Study Instance UID -->
    <attr tag="(0020,000D)"/>
<!-- Study ID -->
    <attr tag="(0020,0010)"/>

<!-- Series Attributes -->
<!-- Series Date -->
    <attr tag="(0008,0021)"/>
<!-- Series Time -->
    <attr tag="(0008,0031)"/>
<!-- Modality -->
    <attr tag="(0008,0060)"/>
<!-- Manufacturer -->
    <attr tag="(0008,0070)"/>
<!-- Series Description -->
    <attr tag="(0008,103E)"/>
<!-- Manufacturer Model Name -->
    <attr tag="(0008,1090)"/>
<!-- Referenced Performed Procedure Step Sequence -->
    <attr tag="(0008,1111)"/>
<!-- Body Part Examined -->
    <attr tag="(0018,0015)"/>
<!-- Series Instance UID -->
    <attr tag="(0020,000E)"/>
<!-- Series Number -->
    <attr tag="(0020,0011)"/>
<!-- Laterality -->
    <attr tag="(0020,0060)"/>
<!-- Performed Procedure Step Start Date -->
    <attr tag="(0040,0244)"/>
<!-- Performed Procedure Step Start Time -->
    <attr tag="(0040,0245)"/>
<!-- Request Attributes Sequence -->
    <attr tag="(0040,0275)"/>
    
<!-- Instance Attributes -->
<!-- Content Sequence -->
    <attr tag="(0040,A730)"/>
    
  </filter>
  
</dcm4jboss-attribute-filter>

=== pacsbrasil/dcm4che2/dcm4chee/dcm4chee-arc/trunk/dcm4jboss-ejb/src/etc/conf/dcm4jboss-attribute-filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dcm4jboss-attribute-filter SYSTEM "dcm4jboss-attribute-filter.dtd">
<dcm4jboss-attribute-filter>
    <filter level="PATIENT">
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00100010"/> <!--  Patient's Name -->
        <attr tag="00100020" coerce="false"/> <!--  Patient ID -->
        <attr tag="00100021"/> <!-- Issuer of Patient ID -->
        <attr tag="00100030"/> <!-- Patient's Birth Date -->
        <attr tag="00100040"/> <!-- Patient's Sex -->
        <attr tag="00102160"/> <!-- Patient Comments -->
    </filter>
    <filter level="STUDY">
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00080020"/> <!-- Study Date -->
        <attr tag="00080030"/> <!-- Study Time -->
        <attr tag="00080050"/> <!-- Accession Number -->
        <attr tag="00080090"/> <!-- Referring Physician Name -->
        <attr tag="00081030"/> <!-- Study Description -->
        <attr tag="00081032"/> <!-- Procedure Code Seq -->
        <attr tag="0020000D" coerce="false"/> <!-- Study Instance UID -->
        <attr tag="00200010"/> <!-- Study ID -->
    </filter>
    <filter level="SERIES">
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00080021"/> <!-- Series Date -->
        <attr tag="00080031"/> <!-- Series Time -->
        <attr tag="00080060"/> <!-- Modality -->
        <attr tag="00080070"/> <!-- Manufacturer -->
        <attr tag="0008103E"/> <!-- Series Description -->
        <attr tag="00081090"/> <!-- Manufacturer Model Name -->
        <attr tag="00081111"/> <!-- Referenced Performed Procedure Step Sequence -->
        <attr tag="00180015"/> <!-- Body Part Examined -->
        <attr tag="0020000E" coerce="false"/> <!-- Series Instance UID -->
        <attr tag="00200011"/> <!-- Series Number -->
        <attr tag="00200060"/> <!-- Laterality -->
        <attr tag="00400244"/> <!-- Performed Procedure Step Start Date -->
        <attr tag="00400245"/> <!-- Performed Procedure Step Start Time -->
        <attr tag="00400275"/> <!-- Request Attributes Sequence -->
    </filter>
    <filter level="IMAGE">
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00080008"/> <!-- Image Type -->
        <attr tag="00080016"/> <!-- SOP Class UID -->
        <attr tag="00080018"/> <!-- SOP Instance UID -->
        <attr tag="00080023"/> <!-- Content Date -->
        <attr tag="00080033"/> <!-- Content Time -->
        <attr tag="00081115"/> <!-- Referenced Series Sequence -->
        <attr tag="00200013"/> <!-- Instance Number -->
        <attr tag="00280004"/> <!-- Photometric Interpretation -->
        <attr tag="00280008"/> <!-- Number of Frames -->
        <attr tag="00280010"/> <!-- Rows -->
        <attr tag="00280011"/> <!-- Columns -->
        <attr tag="00280100"/> <!-- Bits Allocated -->
        <attr tag="0040A032"/> <!-- Observation DateTime -->
        <attr tag="0040A043"/> <!-- Concept Name Code Sequence -->
        <attr tag="0040A073"/> <!-- Verifying Observer Sequence -->
        <attr tag="0040A370"/> <!-- Referenced Request Sequence -->
        <attr tag="0040A491"/> <!-- Completion Flag -->
        <attr tag="0040A493"/> <!-- Verification Flag -->
        <attr tag="00700080"/> <!-- Content Label -->
        <attr tag="00700081"/> <!-- Content Description -->
        <attr tag="00700082"/> <!-- Presentation Creation Date -->
        <attr tag="00700083"/> <!-- Presentation Creation Time -->
        <attr tag="00700084"/> <!-- Content Creator s Name -->
    </filter>
</dcm4jboss-attribute-filter>
