=== pacsbrasil/dcm4che2/dcm4chee/dcm4chee-arc/tags/DCM4JBOSS_0_9_3/dcm4jboss-ejb/src/etc/conf/dcm4jboss-attribute-filter.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
This is the XML DTD for the dcm4jboss attribute filter descriptor.

Minimal descriptor for DICOM Standard Conformance of Query/Retrieve Service:
  <dcm4jboss-attribute-filter>
    <patient>
      <attr tag="(0008,0005)"/>
      <attr tag="(0010,0010)"/>
      <attr tag="(0010,0020)"/>
    </patient>

    <study>
      <attr tag="(0008,0005)"/>
      <attr tag="(0008,0020)"/>
      <attr tag="(0008,0030)"/>
      <attr tag="(0008,0050)"/>
      <attr tag="(0020,000D)"/>
      <attr tag="(0020,0010)"/>
    </study>

    <series>
      <attr tag="(0008,0005)"/>
      <attr tag="(0008,0060)"/>
      <attr tag="(0020,000E)"/>
      <attr tag="(0020,0011)"/>
    </series>

    <instance>
      <attr tag="(0008,0005)"/>
      <attr tag="(0008,0018)"/>
      <attr tag="(0020,0013)"/>
    </instance>
  </dcm4jboss-attribute-filter>
-->

<!ELEMENT dcm4jboss-attribute-filter (patient, study, series, instance)>
<!ELEMENT patient (attr)*>
<!ELEMENT study (attr)*>
<!ELEMENT series (attr)*>
<!ELEMENT instance (attr)*>
<!ELEMENT attr EMPTY>

<!ATTLIST attr tag CDATA #REQUIRED>

=== pacsbrasil/dcm4che2/dcm4chee/dcm4chee-arc/tags/DCM4JBOSS_2_4_2/dcm4jboss-ejb/src/etc/conf/dcm4jboss-minimal-attribute-filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dcm4jboss-attribute-filter SYSTEM "dcm4jboss-attribute-filter.dtd">
<dcm4jboss-attribute-filter>
    <filter level="PATIENT">
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00100010"/> <!--  Patient's Name -->
        <attr tag="00100020"/> <!--  Patient ID -->
    </filter>
    <filter level="STUDY">
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00080020"/> <!-- Study Date -->
        <attr tag="00080030"/> <!-- Study Time -->
        <attr tag="00080050"/> <!-- Accession Number -->
        <attr tag="0020000D" coerce="false"/> <!-- Study Instance UID -->
        <attr tag="00200010"/> <!-- Study ID -->
    </filter>
    <filter level="SERIES">
        <attr tag="00080060"/> <!-- Modality -->
        <attr tag="0020000E" coerce="false"/> <!-- Series Instance UID -->
        <attr tag="00200011"/> <!-- Series Number -->
        <attr tag="00430010"/> <!-- Private Creator ID: dcm4che/archive -->
        <attr tag="00430014"/> <!-- Calling AET (dcm4che/archive private Tag)-->
    </filter>
    <filter level="IMAGE">
        <attr tag="00080018"/> <!-- SOP Instance UID -->
        <attr tag="00200013"/> <!-- Instance Number -->
    </filter>
</dcm4jboss-attribute-filter>
